config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  resources :guests, only: %i[create new update show index]

  # VITRINE
  root "pages#home"
  patch "/home", to: "pages#update"
  get "/pourquoi_parentheze", to: "pages#why"

  # MESSENGER
  get '/welcome', to: 'guests#welcome'
  get "/contact", to: "messengers#contact"
  get "/mini_contact", to: "messengers#mini_contact"
  get "/add_friend", to: "messengers#add_friend"
  get "/ask_for_cards", to: "messengers#ask_for_cards"
  get "/custom_mail", to: "messengers#custom_mail"
  get "/card_for_school", to: "messengers#card_for_school"


  # INSCRIPTION
  devise_for :users, controllers: { registrations: "my_registrations" }

  get '/profiles', to: "profiles#index"

  resources :users, only: %i[] do
    resources :profiles, only: %i[new create show edit update destroy] do
      resources :favorites, only: %i[create destroy]
      member do
        get 'add_friends'
        get 'ask_for_cards'
        get 'card_for_school'
        get 'previous'
        get 'request_update'
        get 'update_wishes'
        get 'validate'
      end
    end
  end

  #JOBS
  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

  # ADMIN
  namespace :admin do
    get '/', to: 'admins#password_check'
    get '/requested', to: 'admins#requested'
    get '/validations', to: 'admins#validations'
    get '/password_verification', to: 'admins#password_verification'
    get '/destroy_profile', to: 'admins#destroy_profile'
    get '/custom_mailer', to: 'admins#custom_mailer'
    get '/session_way', to: 'admins#session_way'
    patch '/session_way', to: 'admins#session_way_update'
    resources :letters, only: %i[index update destroy] do
      member do
        get 'export'
      end
    end
  end

  mount Attachinary::Engine => "/attachinary"

end

app/models/profile.rb
class Profile < ApplicationRecord
  regex_name = /\A[^0-9][\w'\-áéíóúäëïöüÄőŐűŰZàáâäãåąčćęèéêëėįìíîïłńòóôöõøùúûüųūÉÈÊĒÀÄ][^0-9_!.¡?÷?¿+=@#$%^&*(){}|~<>;:\[\]]{0,}\z/
  regex_phone = /(0|\\+33|0033)[1-9][0-9]{8}/

  validates :mother_first_name, format: { with: Regexp.new(regex_name), message: 'Le prénom du parent 1 n\'est pas valide' }, if: :step3?
  validates :father_first_name, format: { with: Regexp.new(regex_name), message: 'Le prénom du parent 2 n\'est pas valide' }, if: :step3?, allow_blank: true
  validates_numericality_of :kids, greater_than: 0, message: 'Vous devez être parent et avoir au moins 1 enfant', if: :step3?
  validates :kids, presence: { message: 'Vous devez être parent et avoir au moins 1 enfant' }, if: :step3?
  validates :phone, format: { with: Regexp.new(regex_phone), message: 'Le numéro de téléphone n\'est pas valide'}, if: :step4?, allow_blank: true
  validates :address, presence: true, :if => :step4?
  validates :photo, presence: true, :if => :step6?

  enum validation: { pending: 0, validated: 1, uncomplete: 2 }

  belongs_to :user

  delegate :email, :admin, to: :user, :allow_nil => true

  alias_attribute :parent1, :mother_first_name
  alias_attribute :parent2, :father_first_name

  has_many :wishes, through: :user
  has_many :favorites

  scope :validated, -> { where(validation: 1) }
  scope :to_validate, -> { where(step: 6, validation: 0) }

  has_attachment :photo

  def step3?
    step == 3
  end

  def step4?
    step == 4
  end

  def step5?
    step == 5
  end

  def step6?
    step == 6
  end

  def self.excluding(id)
    where.not(user_id: id)
  end

  def couple?
    mother_first_name.present? && father_first_name.present?
  end

  def names
    (mother_first_name.present? ? mother_first_name.capitalize : "" ) + (father_first_name.present? ? " & " + father_first_name.capitalize : "" )
  end

  def full_name
    (mother_first_name.present? ? mother_first_name : "" ) + (father_first_name.present? ? " & " + father_first_name : "" ) + (name.present? ? " " + name : "" )
  end

  def favorite_of(favorite)
    favorite.favorites.where(favorite: self).any?
  end
end

app/controllers/profiles_controller.rb
# frozen_string_literal: true

class ProfilesController < ApplicationController
  before_action :user_and_profile, only: %i[create new edit index update previous add_friends ask_for_cards card_for_school update_wishes]
  before_action :params_profile, only: %i[validate destroy request_update show]

  def add_friends; end

  def add_wishes(user, profile)
    user.user_wishes.destroy_all
    wishes = Wish.all.to_a
    wishes.each_with_index do |wish, index|
      UserWish.create(user: user, wish: wish) if profile_params[("need"+index.to_s).to_sym].present?
    end
    profile.save
    redirect_to edit_user_profile_path
  end

  def ask_for_cards; end

  def card_for_school; end

  def destroy; end

  def edit
    #If user come back on edit after receiving request update mail
    if @profile.uncomplete?
      @profile.validation = 0
      @error_label = true
      @profile.save
      flash[:warning] = t('.flash-after-request')
    end
    @profile.save!
    @step = @profile.step
  end

  def index
    @profiles = Profile.validated.excluding(@user.id)
    @profile = @user.profile
  end

  def inscription_done(user)
    UserMailer.new_registration({email: user.email}).deliver_now
    UserMailer.notification({subject: t('.subject'), email: user.email, address: user.address, name: user.names}).deliver_now
  end

  def new
    @profile = @user.profile || Profile.new(user: @user, step: 1, validation: 0)
    @profile.step = 1 if @profile.step < 1
    @profile.save!
    @step = @profile.step
    redirect_to edit_user_profile_path(@user, @profile)
  end

  def previous
    @profile = @user.profile
    @profile.step -= 1
    @profile.save!
    redirect_to edit_user_profile_path(@user)
  end

  def request_update
    UserMailer.request_update({email: @profile.email, profile: @profile.id, updates: request_update_params}).deliver_now
    flash[:notice] = t('.notice')

    if request_update_params[:parent1].present?
      @profile.step = 2
      @profile.parent1 = nil
    elsif request_update_params[:kids].present?
      @profile.step = 2
      @profile.kids = nil
    elsif request_update_params[:parent2].present?
      @profile.step = 2
      @profile.parent2 = nil
    elsif request_update_params[:address].present?
      @profile.step = 3
      @profile.address = nil
    elsif request_update_params[:phone].present?
      @profile.step = 4
      @profile.phone = nil
    else request_update_params[:photo].present?
      @profile.step = 5
      @profile.photo = nil
    end

    if @profile.save
      redirect_to admin_validations_path
    else
      flash[:warning] = "PROBLEM"
      redirect_to admin_validations_path
    end
  end

  def show
    @favorite = Favorite.where(profile: @current_profile, favorite: @profile.id).first
    @wish = Wish.all
  end

  def update
    if @profile.pending?
      @profile.step += 1
      if @profile.update(profile_params)
        redirect_to edit_user_profile_path
        inscription_done(@user) if @profile.step6?
      else
        notice = ''
        @profile.errors.messages.each do |key, value|
          notice += value.first + '. <br/>'
        end
        flash[:warning] = notice
        redirect_to edit_user_profile_path
      end
    elsif @profile.validated?
      if @profile.update(profile_params)
        redirect_to user_profile_path(@user, @profile)
        flash[:notice] = t('.success')
      else
        flash[:warning] = t('.errors.commons')
      end
    end
  end

  def update_wishes
    @user.user_wishes.destroy_all
    wishes = Wish.all.to_a
    wishes.each_with_index do |wish, index|
      UserWish.create(user: @user, wish: wish) if profile_params[("need"+index.to_s).to_sym].present?
    end
    if @profile.step4?
      path = edit_user_profile_path
      @profile.step += 1
      @profile.save
    else
      path = user_profile_path
    end
    redirect_to path
  end

  def validate
    @profile.validation = 1
    if @profile.save
      flash[:notice] = t('.notice')
      redirect_to admin_validations_path
      UserMailer.validation({email: @profile.email}).deliver_now
    else
      flash[:warning] = t('.alert')
      redirect_to admin_validations_path
    end
  end

  private

  def user_and_profile
    @user = current_user
    @profile = @user.profile
  end

  def params_profile
    @profile = Profile.find(params[:id])
    @user = @profile.user
    @current_profile = current_user.profile
  end

  def profile_params
    params.require(:profile).permit(:address, :kids, :mother_first_name, :father_first_name, :phone, :confidence, :comment, :need0, :need1, :need2, :need3, :photo, :lat, :lng )
  end

  def request_update_params
    params.permit(:address, :kids, :parent1, :parent2, :phone, :photo)
  end
end

app/views/profiles/_add_friend_preview.html.erb
<div class="mailer-preview-frame mailer-preview-transform black-on-white">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <%= cl_image_tag ("parentheze/Parentheze_logo_black.svg"), class:"mailer-preview-logo" %>
      </div>
      <div class="col-12 col-md-12 separator-vertical">
        <%= cl_image_tag ( @user.photo.path ), class:"mailer-preview-portrait" %>
        <%= cl_image_tag ("parentheze/invitation_bubble.png"), class:"mailer-preview-bubble" %>
      </div>
      <div class="col-12 col-md-12 col-lg-12 col-xl-9 separator-vertical text-right">
        <%= cl_image_tag ("parentheze/invitation_bubble_2.png"), class:"mailer-preview-bubble" %>
      </div>

      <div class="col-12 col-md-12 col-lg-12 col-xl-9">
        <div class="bar-separator"></div>
      </div>

      <div class="col-12 col-md-12 col-lg-12 col-xl-9 separator-vertical">
        <h3 class="separator-vertical"><%= @user.names + t('.title', verb: @profile.couple? ? "invitent" : "invite") %></h3>
        <p class="separator-vertical"><%= t('.text1') %></p>
        <p class="separator-vertical"><%= t('.text2') %></p>
      </div>

      <div class="col-12 col-md-12 col-lg-12 col-xl-9 separator-vertical">
      <%= link_to t('.btn_text', recipient: @user.names), "https://www.parentheze.com", class:"btn btn-blue separator-vertical" %>
      </div>
      <div class="mailer-preview-bar separator-vertical"></div>

      <div class="col-12 col-md-12 col-lg-12 col-xl-9 ">
        <h5><%= t('.footer.line1') %></h5>
      </div>
    </div>
  </div>
</div>

app/views/profiles/_card_for_school_preview.html.erb
<div class="mailer-preview-frame mailer-preview-transform black-on-white">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <%= cl_image_tag ("parentheze/Parentheze_logo_black.svg"), class:"mailer-preview-logo" %>
      </div>
      <div class="col-12 col-md-12 separator-vertical">
        <%= cl_image_tag ( @user.photo.path ), class:"mailer-preview-portrait" %>
        <%= cl_image_tag ("parentheze/card_for_school_preview_bubble.png"), class:"mailer-preview-bubble" %>
        <p><%= @user.names %></p>
      </div>

      <div class="col-12 col-md-12 separator-vertical">
        <div class="mailer-preview-content">
          <%= t('.content_html') %>
        </div>
      </div>
      <div class="mailer-preview-bar separator-vertical"></div>

      <div class="col-12 col-md-12 col-lg-12 col-xl-9 ">
        <p><%= t('.footer.line1') %></p>
        <p><%= t('.footer.line2') %></p>
      </div>
    </div>
  </div>
</div>

app/views/profiles/_form1.html.erb
<%= simple_form_for [ @user, @profile ] do |f| %>
  <div class="login-fields">
    <h3><%= t('.title') %></h3>
    <p><%= t('.details') %></p>
    <div class="img-illustration text-center">
     <%= image_tag t('.image') %>
    </div>
    <%= f.input :confidence, as: :hidden, input_html: {value: "true"}  %>
  </div>
  <div class="form-actions">

    <%= f.button :submit, t('commons.button.enter'), class:"login-button" %>
    <p class="text-center clickable">
        <%= link_to t('commons.button.previous'), edit_user_registration_path %>
    </p>
  </div>
<% end %>

app/views/profiles/_form2.html.erb
<%= simple_form_for [ @user, @profile ] do |f| %>
  <div class="login-fields">
    <h3><%= t('.title') %></h3>
    <p><%= t('.details') %></p>
    <%= f.input :mother_first_name, required: true, autofocus: true, label: t('.field1') %>
    <%= f.input :father_first_name, required: false, label: t('.field2'), placeholder: t('.placeholder2') %>
    <%= f.input :kids, required: true, label: t('.field3'), placeholder: t('.placeholder3') %>
  </div>
  <div class="form-actions">
    <%= f.button :submit, t('commons.button.next'), class:"login-button" %>
    <p class="text-center clickable">
        <%= link_to t('commons.button.previous'), previous_user_profile_path(@user, @profile) %>
    </p>
  </div>
<% end %>

app/views/profiles/_form3.html.erb
<%= simple_form_for [ @user, @profile ] do |f| %>
  <div class="login-fields">
    <h3><%= t('.title') %></h3>
    <p><%= t('.details') %></p>
    <%= f.input :address, required: true, autofocus: true, as: :text, label: t('.field1'), :input_html => { :rows => 2, :resize => "none" } %>
    <%= f.input :lat, as: :hidden %>
    <%= f.input :lng, as: :hidden %>
    <%= f.input :phone, required: false, label: t('.field2'), placeholder: t('.placeholder2') %>
  </div>
  <div class="form-actions">
    <%= f.button :submit, t('commons.button.next'), class:"login-button" %>
    <p class="text-center clickable">
      <%= link_to t('commons.button.previous'), previous_user_profile_path(@user, @profile)  %></p>
    </p>
  </div>
<% end %>

app/views/profiles/_form4.html.erb
<%= simple_form_for :profile, url: update_wishes_user_profile_path(@user, @profile), method: :get do |f| %>
  <div class="login-fields">
    <h3><%= t('.title') %></h3>
    <p><%= t('.details') %></p>
    <input type="hidden" class="boolean optional" checked="checked" id="noneed" name="profile[noneed]" value="true" />
    <% Wish.all.each do |wish| %>
      <span class="checkbox margin-bottom-medium">
        <input type="checkbox" class="boolean optional" <%= @profile.wishes.include?(wish) ? 'checked="checked"' : "" %> id="<%= wish.number %>" name="profile[need<%= wish.number %>]" value="true" />
        <label for="<%= wish.number %>"><%= wish.name %></label>
      </span>
    <% end %>
  </div>
  <div class="form-actions">
    <%= f.button :submit, t('commons.button.next'), class:"login-button" %>
    <p class="text-center clickable">
      <%= link_to t('commons.button.previous'), previous_user_profile_path(@user, @profile)  %></p>
    </p>
  </div>
<% end %>

app/views/profiles/_form6.html.erb
  <div class="login-fields login-fields-small">
    <h3 class="white"><%= t('.title') %></h3>
    <p class="white"><%= t('.details') %></p>
  </div>
  <div class="form-actions">
    <%= link_to t('commons.button.back_to_root'), root_path, class:"btn btn-blue flexbox" %>
  </div>

app/views/profiles/_invitation.html.erb
<div class="mailer-preview-frame black-on-white">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <%= cl_image_tag ("parentheze/Parentheze_logo_black.svg"), class:"mailer-preview-logo" %>
      </div>
      <div class="col-12 col-md-12 separator-vertical">
        <%= cl_image_tag ("parentheze/inscription_exemple_04.jpg"), class:"mailer-preview-portrait" %>
        <%= cl_image_tag ("parentheze/invitation_bubble.png"), class:"mailer-preview-bubble" %>
      </div>
      <div class="col-12 col-md-12 col-lg-12 col-xl-9 separator-vertical text-right">
        <%= cl_image_tag ("parentheze/invitation_bubble_2.png"), class:"mailer-preview-bubble" %>
      </div>

      <div class="col-12 col-md-12 col-lg-12 col-xl-9">
        <div class="bar-separator"></div>
      </div>

      <div class="col-12 col-md-12 col-lg-12 col-xl-9 separator-vertical">
        <h3 class="separator-vertical"><%= "Maxime et Juliette " + t('.title') %></h3>
        <p class="separator-vertical"><%= t('.text1') %></p>
        <p class="separator-vertical"><%= t('.text2') %></p>
      </div>

      <div class="col-12 col-md-12 col-lg-12 col-xl-9 separator-vertical">
      <%= link_to t('.btn_text'), "https://www.parentheze.com", class:"btn btn-blue separator-vertical" %>
      </div>
      <div class="mailer-preview-bar separator-vertical"></div>

      <div class="col-12 col-md-12 col-lg-12 col-xl-9 ">
        <h5><%= t('.footer.line1') %></h5>
      </div>
    </div>
  </div>
</div>

app/views/profiles/_mosaic.html.erb
<div class="col-12 col-md-8 col-lg-8 col-xl-9">
  <div class="row">
    <div class="col-12">
      <h5><%= t('.title') %></h5>
    </div>
    <% @profiles.each do |profile| %>
      <div class="col-12 col-sm-6 col-md-6 col-lg-4 col-xl-3">
        <%= render "shared/profile_card", profile: profile, reputation: "Bonne réputation", distance: "200 mètres" %>
      </div>
    <% end %>
    <div class="col-12 col-sm-6 col-md-6 col-lg-4 col-xl-3">
      <%= render "shared/profile_card_invitation", content: {
                                                    image: t('card.invitation.image'),
                                                    title: t('card.invitation.title'),
                                                    text1: t('card.invitation.text1'),
                                                    text2: t('card.invitation.text2'),
                                                    link: add_friends_user_profile_path(@user, @profile),
                                                    promotion: false,
                                                    free: false } %>
    </div>
    <div class="col-12 col-sm-6 col-md-6 col-lg-4 col-xl-3">
      <%= render "shared/profile_card_invitation", content: {
                                                    image: t('card.school.image'),
                                                    title: t('card.school.title'),
                                                    text1: t('card.school.text1'),
                                                    text2: t('card.school.text2'),
                                                    link: card_for_school_user_profile_path(@user, @profile),
                                                    promotion: true,
                                                    free: true } %>
    </div>
    <div class="col-12 col-sm-6 col-md-6 col-lg-4 col-xl-3">
      <%= render "shared/profile_card_invitation", content: {
                                                    image: t('card.visitcard.image'),
                                                    title: t('card.visitcard.title'),
                                                    text1: t('card.visitcard.text1'),
                                                    text2: t('card.visitcard.text2'),
                                                    link: ask_for_cards_user_profile_path(@user, @profile),
                                                    promotion: true,
                                                    free: true } %>
    </div>
    <% 3.times do %>
      <div class="col-12 col-sm-6 col-md-6 col-lg-4 col-xl-3">
        <%= render "shared/profile_card_empty" %>
      </div>
    <% end %>
  </div>
</div>

app/views/profiles/_self_profile.html.erb
<div class="col-12 col-md-4 col-lg-3 col-xl-3">
  <div class="row">
    <div class="col-12">
      <h5><%= t('.title') %></h5>
      <%= render "shared/profile_card", profile: current_user.profile, reputation: "Bonne réputation", distance: "200 mètres" %>
    </div>
  </div>
</div>

app/views/profiles/add_friend.html.erb
<div class="flex-parent"> <!-- for IE bug -->
  <div class="fullscreen relative white-on-purple mosaic">
    <%= render "shared/pastille_action", path: root_path, icon: "fas fa-glass-martini", color: "yellow", class: "pastille_action" %>
    <div class="container">
      <div class="row">
        <%= render "header" %>
        <%= render "self_profile" %>
        <%= render "add_friend" %>
      </div>
    </div>
  </div>
</div>

app/views/profiles/edit.html.erb
<% content_for(:title_tag) { t('.title') } %>

<div class="flex-parent"> <!-- for IE bug -->
  <div class="fullscreen relative flexbox text-left" style="background-image: linear-gradient(0deg, rgba(10,10,10,0.5) 0%, rgba(10,10,10,0.5) 100%), url(<%= t('.image') %>)">
    <div class="parentheze-login">
      <%= render 'shared/sign_out_button' %>
      <% if @step < 6 %>
      <h4><%= t('.title') %></h4>
        <%= render "shared/breadcrumb", step: @step, length: 5 %>
      <% end %>

      <% %w(1 2 3 4 5 6).each do |step| %>
        <% if @step == step.to_i %>
          <div class="login-box <%= "expandOpen" if step == "6" %>" style="background-image: url(<%= t('.card-image') if step == "6" %>)">
            <%= render 'form'+step, step: step %>
          </div>
        <% end %>
      <% end %>

    </div>
  </div>
</div>

app/views/profiles/index.html.erb
<div class="fullscreen relative mosaic">
  <%= render "shared/pastille_action", path: root_path, icon: "fas fa-glass-martini", color: "yellow", class: "pastille_action" %>
  <div class="container">
    <div class="row">
      <div class="col-12">
        <div class="mosaic-header"></div>
      </div>
      <div class="col-12 col-sm-12 col-md-4 col-lg-3 col-xl-3">
          <div class="row">
            <div class="col-12 col-sm-12">
              <h5><%= t('.column1-title') %></h5>

              <%= render "shared/profile_card", profile: @profile, reputation: "Bonne réputation", distance: "200 mètres" %>
            </div>
        </div>
      </div>
      <div class="col-12 col-sm-12 col-md-8 col-lg-8 col-xl-9">
          <div class="row">
            <div class="col-12">
              <h5><%= t('.column2-title') %></h5>
            </div>
            <% @profiles.each do |profile| %>
              <div class="col-12 col-sm-6 col-md-6 col-lg-4 col-xl-3">
                <%= render "shared/profile_card", profile: profile, reputation: "Bonne réputation", distance: "200 mètres" %>
              </div>
            <% end %>
              <div class="col-12 col-sm-6 col-md-6 col-lg-4 col-xl-3">
                <%= render "shared/profile_card_invitation", image: t('card.invitation.image'),
                                                             title: t('card.invitation.title'),
                                                             text1: t('card.invitation.text1'),
                                                             text2: t('card.invitation.text2'),
                                                             link: root_path,
                                                             promotion: false %>
              </div>
              <div class="col-12 col-sm-6 col-md-6 col-lg-4 col-xl-3">
                <%= render "shared/profile_card_invitation", image: t('card.school.image'),
                                                         title: t('card.school.title'),
                                                         text1: t('card.school.text1'),
                                                         text2: t('card.school.text2'),
                                                         link: root_path,
                                                         promotion: true %>
              </div>
              <div class="col-12 col-sm-6 col-md-6 col-lg-4 col-xl-3">
                <%= render "shared/profile_card_invitation", image: t('card.visitcard.image'),
                                                         title: t('card.visitcard.title'),
                                                         text1: t('card.visitcard.text1'),
                                                         text2: t('card.visitcard.text2'),
                                                         link: root_path,
                                                         promotion: true %>
              </div>
            <% 3.times do %>
              <div class="col-12 col-sm-6 col-md-6 col-lg-4 col-xl-3">
                <%= render "shared/profile_card_empty" %>
              </div>
            <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<%= render "shared/over_footer" %>
<%= render "shared/footer" %>

app/views/profiles/show.html.erb
<% content_for(:title_tag) { t('.title') } %>

<div class="flex-parent"> <!-- for IE bug -->
  <div class="fullscreen relative white-on-purple mosaic">
    <%= render "shared/buttons", mosaic: false, action: true %>
    <div class="container">
      <div class="row">
        <%= render "header" %>
        <%= render "self_profile" %>
        <%= render "profile" %>
      </div>
    </div>
  </div>
</div>
<%= render "shared/over_footer" %>