config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  resources :guests, only: %i[create new update show index]

  # VITRINE
  root "pages#home"
  patch "/home", to: "pages#update"
  get "/pourquoi_parentheze", to: "pages#why"

  # MESSENGER
  get '/welcome', to: 'guests#welcome'
  get "/contact", to: "messengers#contact"
  get "/mini_contact", to: "messengers#mini_contact"
  get "/add_friend", to: "messengers#add_friend"
  get "/ask_for_cards", to: "messengers#ask_for_cards"
  get "/custom_mail", to: "messengers#custom_mail"
  get "/card_for_school", to: "messengers#card_for_school"


  # INSCRIPTION
  devise_for :users, controllers: { registrations: "my_registrations" }

  get '/profiles', to: "profiles#index"

  resources :users, only: %i[] do
    resources :profiles, only: %i[new create show edit update destroy] do
      resources :favorites, only: %i[create destroy]
      member do
        get 'add_friends'
        get 'ask_for_cards'
        get 'card_for_school'
        get 'previous'
        get 'request_update'
        get 'update_wishes'
        get 'validate'
      end
    end
  end

  #JOBS
  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

  # ADMIN
  namespace :admin do
    get '/', to: 'admins#password_check'
    get '/requested', to: 'admins#requested'
    get '/validations', to: 'admins#validations'
    get '/password_verification', to: 'admins#password_verification'
    get '/destroy_profile', to: 'admins#destroy_profile'
    get '/custom_mailer', to: 'admins#custom_mailer'
    get '/session_way', to: 'admins#session_way'
    patch '/session_way', to: 'admins#session_way_update'
    resources :letters, only: %i[index update destroy] do
      member do
        get 'export'
      end
    end
  end

  mount Attachinary::Engine => "/attachinary"

end

app/views/shared/_breadcrumb.html.erb
<div class="breadcrumb">
  <% (1..length).each do |x| %>
    <div class="step <%= "active" if x == step %>"><%= x %></div>
  <% end %>
</div>

app/views/shared/_button_action.html.erb
<%= link_to(content_tag(:i, nil, class: 'fa', id:'pastille'), root_path, class: "pastille pastille-yellow flexbox" ) %>

<%= content_for :after_js do %>
  <script>
    function hand() {
      var a;
      a = document.getElementById("pastille");
      a.innerHTML = "&#xf25a;";
      setTimeout(function () {
          a.innerHTML = "&#xf1ae;";
        }, 1500);
      setTimeout(function () {
          a.innerHTML = "&#xf000;";
        }, 2000);
      setTimeout(function () {
          a.innerHTML = "&#xf0f4;";
        }, 2500);
    }
    hand();
    setInterval(hand, 3000);
  </script>
<% end %>

app/views/shared/_button_close.html.erb
<%= link_to(content_tag(:i, nil, class: 'fas fa-times'), profiles_path, class: "pastille pastille-white pastille-close flexbox" ) %>

app/views/shared/_button_mosaic.html.erb
<%= link_to(content_tag(:i, nil, class: 'fas fa-th'), profiles_path, class: "pastille pastille-#{color} flexbox" ) %>

app/views/shared/_button_with_icon.html.erb
<%= link_to path:locals[:path], method:locals[:method], class:locals[:klass], remote:locals[:remote] do %>
  <div class="<%= locals[:klass] %>">
    <p><i class="far <%= locals[:icon] %>"></i><%= locals[:text] %></p>
  </div>
<% end %>

app/views/shared/_contact_form.html.erb
<div class="contact-form black-on-white center">
  <div class="contact-header"></div>
  <div class="container">
    <div class="row">
      <div class="contact-identity col-12 col-sm-5">
        <h3><%= t('.title') %></h3>
        <div class="bar"></div>
        <%= simple_form_for :message, url: contact_path, method: :get do |f| %>
        <div class="margin-bottom-medium">
          <p> <%= t('.identity.field1') %></p>
          <%= f.input :name, label: false, input_html: {value: session[:contact_name] || "" } %>
          <p><%= t('.identity.field2') %></p>
          <%= f.input :email, label: false, input_html: {value: session[:contact_email] || "", class:"email-field"} %>

        </div>
         <label class="checkbox">
           <input type="checkbox" class="boolean optional" id="iamhuman" name="iamhuman" value="1" />
           <label for="iamhuman"><%= t('.identity.checkbox') %></label>
         </label>
      </div>
      <div class="contact-message col-12 col-sm-7">
        <p><%= t('.message.title') %></p>
          <%= f.input :comment, label: false, id: "textarea", as: :text, :input_html => { cols: 5,
                                                                                          rows: 10,
                                                                                          placeholder: t('.message.placeholder'),
                                                                                          resize: "none",
                                                                                          value: session[:contact_comment] || "" } %>
          <%= f.button :submit, value: t('.message.button_text'), data: { disable_with: "" }, class:"contact-button" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_cookie_approval.html.erb
<a class="slide-away">
  <div class="flexbox" id="cookie-label">
    <i class="fa fa-times slide-away"></i>
    <div class="cookie-content">
      <div class="flexbox">
        <%= image_tag t('.image') %>
      </div>
      <div>
        <p><%= t('.text') %></p>
        <p><strong> <%= t('.button1_text') %></strong><strong><span id="know-more"><%= t('.button2_text') %></span></strong></p>
      </div>
    </div>
  </div>
</a>

<%= content_for :after_js do %>
  <script>
    $(document).ready(function(){
      $('.slide-away').on('click', function(){
        slideAway();
      })
    })
    function slideAway() {
      $("#cookie-label").addClass('slideDownOut');
      setTimeout(function(){
        $('#cookie-label').remove();
      }, 1000);
    }
  </script>
<% end %>

app/views/shared/_flashes.html.erb
<% flash.each do |key, value| %>
  <div class="alert position-<%= key[-1] %> slideLeft-nobounce<%= key[-1] %>" role="alert">
    <div class="alert-badge alert-<%= key %> flexbox">
      <i class="<%= flash_icon(key) %> bigEntrance withdelay" aria-hidden="true"></i>
    </div>
    <div class="alert-message text-left flexbox">
      <%= simple_format(value) %>
    </div>
    <div type="button" class="alert-close" data-dismiss="alert" aria-label="close"><i class="fa fa-times close-<%= key %>" aria-hidden="true"></i></div>
  </div>
<% end %>

app/views/shared/_mini_form.html.erb
<div class="full-width">
  <%= simple_form_for :message, url: content[:path], method: :get do |f| %>
    <div class="col-12 col-sm-8">
      <%= f.input :comment, label: content[:label], placeholder: content[:placeholder], input_html: {value: content[:value] || "" }  %>
    </div>
    <div class="col-12 col-sm-4">
    <%= f.button :submit, value: content[:btn_text], data: { disable_with: "" }, class:"btn btn-blue" %>
    </div>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon" id="top">
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= cl_image_tag "parentheze/Parentheze_logo.svg" %>
  <% end %>

  <div class="navbar-wagon-right d-none d-lg-block">
    <% if $session_way %>
      <% if user_signed_in? %>
        <%= link_to t('.sign_out'), destroy_user_session_path,  method: :delete, class: "navbar-wagon-item navbar-wagon-link" %>
      <% else %>
        <%= link_to t('.why'), pourquoi_parentheze_path, class: "navbar-wagon-item navbar-wagon-link" %>
        <%= link_to t('.plans'), "/#slide2", class: "navbar-wagon-item navbar-wagon-link" %>
        <%= link_to t('.sign_in'), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <% end %>
    <% else %>
      <%= link_to t('.why'), pourquoi_parentheze_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to t('.plans'), "/#slide2", class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <div class="navbar-wagon-item d-block d-lg-none">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to t('.why'), pourquoi_parentheze_path, class: "navbar-wagon-item flexbox" %></li>
        <li><%= link_to t('.plans'), "/#slide2", class: "navbar-wagon-item flexbox" %></li>
        <% if $session_way %>
          <% if user_signed_in? %>
            <li><%= link_to t('.sign_out'), destroy_user_session_path,  method: :delete , class: "navbar-wagon-item flexbox"%></li>
          <% else %>
            <li><%= link_to t('.sign_in'), new_user_session_path, class: "navbar-wagon-item flexbox" %></li>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_over_footer.html.erb
<div class="over-footer text-center">
  <h4 class="margin-bottom-medium"><%= t('.title') %></h4>
  <div class="over-footer-form black-on-white center margin-bottom-medium" id="over-footer">
      <%= simple_form_for :message, url: mini_contact_path, method: :get do |f| %>
        <%= f.input :comment, label: false, id: "textarea", as: :text, :input_html => { cols: 5,
                                                                                        rows: 3,
                                                                                        placeholder: t('.placeholder'),
                                                                                        resize: "none",
                                                                                        value: session[:contact_comment] || "" } %>
        <%= f.button :submit, value: t('commons.button.send'), data: { disable_with: "" }, class:"over-footer-button" %>
      <% end %>
  </div>
  <div class="footer-line-dark"></div>
  <div class="footer-line-light"></div>
</div>

app/views/shared/_profile_card_empty.html.erb
<%= link_to root_path do %>
  <div class="profile-card empty">
    <div class="profile-card-portrait" style="background-image: url('<%= cl_image_path "parentheze/profile-card-invitation2.png" %>')">
    </div>
  </div>
<% end %>

app/views/shared/_profile_card_invitation.html.erb
<%= link_to content[:link] do %>
  <div class="profile-card">
    <% if content[:promotion] == true %>
      <div class="card-promotion"><%= t('card.promotion') %></div>
    <% end %>
    <% if content[:free] == true %>
      <div class="card-free"><%= t('card.free') %></div>
    <% end %>
    <div class="profile-card-portrait" style="background-image: url('<%= cl_image_path content[:image] %>')">
    </div>
    <div class="profile-card-description text-center">
      <h5 class="name"><%= content[:title] %></h5>
      <h5 class="reputation"><%= content[:text1] %></h5>
      <h5 class="reputation"><%= content[:text2] %></h5>
    </div>
  </div>
<% end %>

app/views/shared/_profile_card_vide.html.erb
<%= link_to root_path do %>
  <div class="profile-card">
    <div class="profile-card-portrait" style="background-image: url('<%= cl_image_path "parentheze/profile-card-invitation.png" %>')">
    </div>
    <div class="profile-card-description text-center">
      <h5 class="name"><%= t('.title') %></h5>
      <h5 class="reputation"><%= t('.reputation') %></h5>
    </div>
  </div>
<% end %>