config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  resources :guests, only: %i[create new update show index]

  # VITRINE
  root "pages#home"
  patch "/home", to: "pages#update"
  get "/pourquoi_parentheze", to: "pages#why"

  # MESSENGER
  get '/welcome', to: 'guests#welcome'
  get "/contact", to: "messengers#contact"
  get "/mini_contact", to: "messengers#mini_contact"
  get "/add_friend", to: "messengers#add_friend"
  get "/ask_for_cards", to: "messengers#ask_for_cards"
  get "/custom_mail", to: "messengers#custom_mail"
  get "/card_for_school", to: "messengers#card_for_school"


  # INSCRIPTION
  devise_for :users, controllers: { registrations: "my_registrations" }

  get '/profiles', to: "profiles#index"

  resources :users, only: %i[] do
    resources :profiles, only: %i[new create show edit update destroy] do
      resources :favorites, only: %i[create destroy]
      member do
        get 'add_friends'
        get 'ask_for_cards'
        get 'card_for_school'
        get 'previous'
        get 'request_update'
        get 'update_wishes'
        get 'validate'
      end
    end
  end

  #JOBS
  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

  # ADMIN
  namespace :admin do
    get '/', to: 'admins#password_check'
    get '/requested', to: 'admins#requested'
    get '/validations', to: 'admins#validations'
    get '/password_verification', to: 'admins#password_verification'
    get '/destroy_profile', to: 'admins#destroy_profile'
    get '/custom_mailer', to: 'admins#custom_mailer'
    get '/session_way', to: 'admins#session_way'
    patch '/session_way', to: 'admins#session_way_update'
    resources :letters, only: %i[index update destroy] do
      member do
        get 'export'
      end
    end
  end

  mount Attachinary::Engine => "/attachinary"

end

app/views/admin/admins/_profile.html.erb
<%= simple_form_for :profile, url: request_update_user_profile_path(profile.user, profile), method: :get do |f| %>
  <div class="card">
    <p><%= t('.card_title') %></p>
    <div class="row margin-bottom-medium">
      <div class="col-xs-12 col-md-9">
        <div class="row">
          <div class="col-xs-12 col-md-4 ">
            <label class="checkbox">
              <input type="checkbox" class="boolean optional" id="parent1-<%= profile.id %>" name="parent1" value="true" />
            <label for="parent1-<%= profile.id %>"><p><%= t('.field1') %></p></label>
            </label>
          </div>
          <div class="col-xs-12 col-md-4 ">
            <p class="align-to-checkbox"><%= profile.parent1 %></p>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-12 col-md-4 ">
            <label class="checkbox">
              <input type="checkbox" class="boolean optional" id="parent2-<%= profile.id %>" name="parent2" value="true" />
            <label for="parent2-<%= profile.id %>"><p><%= t('.field2') %></p></label>
            </label>
          </div>
          <div class="col-xs-12 col-md-4 ">
            <p class="align-to-checkbox"><%= profile.parent2 %></p>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-12 col-md-4 ">
            <label class="checkbox">
              <input type="checkbox" class="boolean optional" id="kids-<%= profile.id %>" name="kids" value="true" />
            <label for="kids-<%= profile.id %>"><p><%= t('.field3') %></p></label>
            </label>
          </div>
          <div class="col-xs-12 col-md-4 ">
            <p class="align-to-checkbox"><%= profile.kids %></p>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-12 col-md-4 ">
            <label class="checkbox">
              <input type="checkbox" class="boolean optional" id="address-<%= profile.id %>" name="address" value="true" />
            <label for="address-<%= profile.id %>"><p><%= t('.field4') %></p></label>
            </label>
          </div>
          <div class="col-xs-12 col-md-4 ">
            <p class="align-to-checkbox"><%= profile.address %></p>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-12 col-md-4 ">
            <label class="checkbox">
              <input type="checkbox" class="boolean optional" id="phone-<%= profile.id %>" name="phone" value="true" />
            <label for="phone-<%= profile.id %>"><p><%= t('.field5') %></p></label>
            </label>
          </div>
          <div class="col-xs-12 col-md-4 ">
            <p class="align-to-checkbox"><%= profile.phone %></p>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-12 col-md-4 ">
            <label class="checkbox">
              <input type="checkbox" class="boolean optional" id="photo-<%= profile.id %>" name="photo" value="true" />
            <label for="photo-<%= profile.id %>"><p><%= t('.field7') %></p></label>
            </label>
          </div>
          <div class="col-xs-12 col-md-4 ">
            <p class="align-to-checkbox"><%= profile.photo %></p>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-12 col-md-12 ">
            <p><%= t('.field6') %></p>
            <div class="row">
            <% profile.wishes.each do |wish| %>
              <div class="col-xs-12 col-md-3">
                <p><%= wish.name %></p>
              </div>
            <% end %>
            </div>
          </div>
          <div class="col-xs-12 col-md-4 ">
            <p></p>
          </div>
        </div>
      </div>
      <div class="col-xs-12 col-md-3">
      <% if profile.photo? %>
        <%= cl_image_tag profile.photo.path, width: 225, height: 150, crop: :fill %>
      <% end %>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 col-md-3">
        <%= link_to t('.btn_text1'), validate_user_profile_path(profile.user, profile), class:"btn btn-green", data: {confirm: 'Are you sure?'} %>
      </div>
      <div class="col-xs-12 col-md-3">
        <%= f.button :submit, t('.btn_text2'), class:"btn btn-orange", data: {confirm: 'Are you sure?'} %>
      </div>
      <div class="col-xs-12 col-md-3">
        <%= link_to t('.btn_text3'), admin_destroy_profile_path(profile.id), class:"btn btn-green", data: {confirm: 'Are you sure?'} %>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/admins/_profiles.html.erb
<div class="dashboard">
  <div class="container">
    <div class="row margin-bottom-small">
      <%= render "admin/shared/tabs" %>
    </div>

    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <div class="padding-box">
         <p class="white" %><%= t('.nothing_here') if @profiles.size == 0 %></p>
        </div>
        <% @profiles.each do |profile| %>
          <%= render "profile", profile: profile %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/admins/custom_mailer.html.erb
<div class="dashboard">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <%= render "admin/shared/tabs" %>
      </div>

      <div class="col-12">
        <div class="row">
          <div class="col-12">
            <div class="page-wrapper black-on-white margin-bottom-big relative">
              <div class="container">
                <div class="row">
                  <div class="pastille pastille-yellow pastille-close flexbox clickable" id="erase"><i class="fas fa-eraser"></i></div>
                  <div class="col-12">
                    <h3><%= t('.title') %></h3>
                  </div>
                  <div class="col-12">
                    <%= simple_form_for :message, url: custom_mail_path, method: :get do |f| %>
                      <%= f.input :recipient, collection: @recipient, prompt: "Sélectionner le(s) Destinataire(s)", required: :true, label: "Destinataire(s) : ", input_html: { value: @session["recipient"] } %>
                      <%= f.input :subject, label: "Sujet : ", input_html: { value: @session["subject"] } %>
                      <%= f.input :photo, label: "Lien de la photo à inclure :", required: false, input_html: { value: @session["photo"]} %>
                      <%= f.input :comment, label: "Corps du message : (Séparer les paragraphes par #) ", id: "textarea",
                                                                          as: :text,
                                                                          input_html: {  cols: 12,
                                                                                         rows: 15,
                                                                                         resize: "none",
                                                                                         value: @session["comment"]
                                                                                          } %>
                      <%= f.input :btn_text, label: "Texte du bouton : ", required: false, input_html: { value: @session["btn_text"]} %>
                      <%= f.input :btn_link, label: "Lien du bouton : ", required: false, input_html: { value: @session["btn_link"] } %>
                      <button type="button" id="submit" class="btn btn-blue" data-toggle="modal" data-target="#exampleModal">
                        Envoyer
                      </button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

  <!-- Modal -->
  <div class="modal fade mailer-preview mailer-preview-notransform" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content mailer-preview-frame" style="width: 600px">
        <div class="modal-header">
          <h4 class="modal-title" id="exampleModalLabel">Aperçu du mail</h4>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div>
          <p>Destinataires : </p>
          <p class="underline" id="recipient"> </p>
          <p>Sujet :</p>
          <p class="underline" id="subject" ></p>
          <div class="full-width separator-vertical">
            <%= image_tag "https://res.cloudinary.com/doodlid/image/upload/v1518618244/parentheze/Parentheze_logo_black.png", class:"mailer-preview-logo" %>
          </div>
          <p id="comment"></p>
          <div class="separator-vertical">
            <%= link_to '', "http://www.ecosia.org", id:"btn", class:"btn btn-yellow" %>
          </div>

          <%= image_tag "https://res.cloudinary.com/doodlid/image/upload/v1519923591/parentheze/polaroid_mail_photo02.png", class:"mailer-preview-photo", id:"photo" %>

          <%= render "user_mailer/onboarding/footer" %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <%= f.button :submit, value: "Double check et envoie", class:"btn btn-yellow" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

<%= content_for :after_js do %>
  <script>
    var submit = document.getElementById('submit');
    var eraser = document.getElementById('erase');
    var btn = document.getElementById('btn');

    submit.addEventListener('click', fillFields);
    eraser.addEventListener('click', emptyFields);

    function emptyFields() {
      document.getElementById('message_recipient').value = "";
      document.getElementById('message_subject').value = "";
      document.getElementById('message_comment').value = "";
      document.getElementById('message_photo').value = "";
      document.getElementById('message_btn_text').value = "";
      document.getElementById('message_btn_link').value = "";
    }

    function fillFields() {
      $('#recipient').html($('#message_recipient').val());
      $('#subject').html($('#message_subject').val());
      $('#comment').html($('#message_comment').val());
      $('#photo').attr('src', $('#message_photo').val());
      $('#btn').html($('#message_btn_text').val());
      btn.setAttribute('href', ($('#message_btn_link').val()));
    }

  </script>
<% end %>

app/views/admin/admins/letters.html.erb
<div class="dashboard">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <%= render "tabs" %>
      </div>

      <div class="col-12">
        <div class="row">
          <div class="col-12">
            <div class="page-wrapper black-on-white margin-bottom-big relative">
              <div class="container">
                <div class="row">

                  <div class="col-12">
                    <h3 class="margin-bottom-big"><%= t('.title') %></h3>
                  </div>
                  <% @letters.each do |letter| %>
                    <div class="col-12 underline margin-bottom-medium">
                      <div class="flex-line">
                        <div>
                          <p>Type: <%= letter.name %></p>
                          <p>Prénoms: <%= letter.user.names %></p>
                          <p>Adresse: <%= letter.address %></p>
                        </div>
                        <div>
                          <% if letter.to_send? %>
                            <%= link_to content_tag(:i, nil, class:'fas fa-check'), root_path, class: "pastille pastille-green flexbox" %>
                          <% elsif letter.sent? %>
                            <i class="fas fa-check green"></i>
                          <% elsif letter.to_trash? %>
                            <i class="fas fa-trash"></i>
                          <% end %>
                        </div>
                      </div>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/admins/password_check.html.erb
<% content_for(:title_tag) { t('.title') } %>

<div class="dashboard">
  <div class="dashboard-container">
    <div class="container">
      <div class="row relative">
        <div class="col-xs-12 col-md-6 offset-md-3">
          <div class="form-picto">
            <i class="fa fa-key"></i>
          </div>
          <%= render "shared/field_with_button", url: admin_password_verification_path, query: "query", subquery: :password, placeholder: t('.placeholder'), btn_text: t('.btn_text'), method: :get %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/admins/requested.html.erb
<% content_for(:title_tag) { t('.title') } %>

<%= render "profiles" %>

app/views/admin/admins/session_way.html.erb
<div class="dashboard">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <%= render "admin/shared/tabs" %>
      </div>

      <div class="col-12">
        <div class="row">
          <div class="col-12">
            <div class="page-wrapper black-on-white margin-bottom-big relative">
              <div class="container">
                <div class="row">
                  <div class="col-12">
                    <h3><%= t('.title') %></h3>
                  </div>

                  <div class="col-12">
                    <div class="col-12 underline margin-bottom-medium">
                      <div class="flex-line">
                        <div>
                          <p><%= t('.way1') %> <%= $session_way %> </p>
                        </div>
                        <div>
                          <% if $session_way %>
                            <%= link_to content_tag(:i, nil, class:'fas fa-times'), admin_session_way_path, method: :patch, data: { confirm: "ATTENTION!" }, class: "pastille pastille-red flexbox" %>
                          <% else %>
                            <%= link_to content_tag(:i, nil, class:'fas fa-check'), admin_session_way_path, method: :patch, class: "pastille pastille-green flexbox" %>
                          <% end %>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/admins/validations.html.erb
<% content_for(:title_tag) { t('.title') } %>

<%= render "profiles" %>